version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - labelstudio
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
      - "443:443"
    environment:
      - NGINX_HOST=data.intelliprove.com
      - NGINX_PORT=80

  labelstudio:
    container_name: labelstudio
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - JSON_LOG=1
      - LOG_LEVEL=DEBUG
    volumes:
      - ./mydata:/label-studio/data:rw

    command: label-studio-uwsgi

